/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dns;

public class DnsApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new DnsApp().getGreeting());
    }
}
